### ISSUE TITLE
`jsont`appears to depend on `bytesrw` even if it wasn't build with support for it

### ISSUE THREAD

**Issue by voodoos** [dbuenzli/jsont#3]
This might be related to #2.

I was able to install `jsont` on a mac M1 with `opam install jsont` without having `bytesrw` installed.

When adding `jsont` to the `libraries` field of one of the `dune` files in an existing project I got this error:

```
********** NEW BUILD (lib/data_source/dune changed) **********

File "~/.opam/5.2.0/lib/jsont/META", line 1, characters 0-0:
Error: Library "bytesrw" not found.
-> required by library "jsont" in ~/.opam/5.2.0/lib/jsont
 ```

Then I tried to install `bytesrw` which triggered a rebuild of `jsont` that failed with an error related to `b0`, similar as in #2, but slightly different:

```
File "test/jsont_tool.ml", line 22, characters 34-39:
22 |   let* git = Os.Cmd.get (Cmd.tool "git") in
                                       ^^^^^
Error: This expression has type "string" but an expression was expected of type
         "B0_std.Cmd.t"
Command exited with code 2.
pkg.ml: [ERROR] cmd ['ocamlbuild' '-use-ocamlfind' '-classic-display' '-j' '4' '-tag' 'debug'
     '-build-dir' '_build' 'opam' 'pkg/META' 'CHANGES.md' 'LICENSE.md'
     'README.md' 'src/jsont.a' 'src/jsont.cmxs' 'src/jsont.cmxa'
     'src/jsont.cma' 'src/jsont.cmx' 'src/jsont.cmi' 'src/jsont.mli'
     'src/jsont_base.cmx' 'src/bytesrw/jsont_bytesrw.a'
     'src/bytesrw/jsont_bytesrw.cmxs' 'src/bytesrw/jsont_bytesrw.cmxa'
     'src/bytesrw/jsont_bytesrw.cma' 'src/bytesrw/jsont_bytesrw.cmx'
     'src/bytesrw/jsont_bytesrw.cmi' 'src/bytesrw/jsont_bytesrw.mli'
     'src/brr/jsont_brr.a' 'src/brr/jsont_brr.cmxs' 'src/brr/jsont_brr.cmxa'
     'src/brr/jsont_brr.cma' 'src/brr/jsont_brr.cmx' 'src/brr/jsont_brr.cmi'
     'src/brr/jsont_brr.mli' 'doc/index.mld' 'doc/cookbook.mld'
     'test/jsont_tool.native']: exited with 10
```

(right, I have `b0` installed in my switch already, that's why I don't get the `b0 missing` error)

**Comment by dbuenzli** [comment]
Yes this is due to the fact that `bytesrw` is a depopt and I messed up the release. You should pin `b0` for now. But you may also want to wait on the outcome of #2 which I plan to settle down until the end of the week. I'll clsoe this in favour of #1.

**Comment by dbuenzli** [comment]
https://github.com/ocaml/opam-repository/pull/27040 should solve the build problems

In the end I haven't made a decision on #2 yet and it may take longer to settle. In any case I hope to be able to keep the existing API would a concrete syntax appear at some point.

**Comment by voodoos** [comment]
Thanks for the update, this did solve the opam installation errors.

However I am still confronted to the original issue: in a switch where I don't have `bytesrw`  installed, and thus installed `jsont`  without support for it, I cannot depend on `jsont` in a project without getting the following error:

```
$ cat dune-project
(lang dune 3.0)

$ cat dune
 (executable
  (name test)
  (libraries jsont))

$ cat test.ml
<empty>

$ dune build
File "_opam/lib/jsont/META", line 1, characters 0-0:
Error: Library "bytesrw" not found.
-> required by library "jsont" in _opam/lib/jsont
-> required by executable test in dune:2
-> required by _build/default/test.exe
-> required by alias all
-> required by alias default
``` 

It builds fine if I install `bytesrw` (which makes for a very simple workaround for now).

**Comment by dbuenzli** [comment]
Ah crap

**Comment by dbuenzli** [comment]
Thanks! I should have read you more carefully. Indeed `bytesrw` was registered as a dependency of `jsont` even though it's not needed (orginally the codec was not in another library).

**Comment by dbuenzli** [comment]
Also, if one day you need the fix and no release has been made just ping me.
