### ISSUE TITLE
Jsont.zero doesn't encode

### ISSUE THREAD

**Issue by amongonz** [dbuenzli/jsont#6]
`Jsont.zero` is documented as encoding all values to `null`, but any encoding fails with "No encoder for ignore base map".

I suspect this is because [the encoder goes through `Repr.Null Base.ignore`](https://github.com/dbuenzli/jsont/blob/68d82983695e7ca34282c1a29384a31ad383a830/src/jsont.ml#L1247-L1251) instead of an equivalent to `Jsont.null`, so [it eventually reaches `Error.no_encoder`](https://github.com/dbuenzli/jsont/blob/68d82983695e7ca34282c1a29384a31ad383a830/src/jsont.ml#L523-L525).

**Comment by dbuenzli** [comment]
Thanks for the report!
